version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    ignore:
      # uses-sdk:minSdkVersion 15 cannot be smaller than version 21 declared in library [androidx.constraintlayout:constraintlayout:2.2.1]
      - dependency-name: "androidx.constraintlayout:constraintlayout"
        versions: [">=2.2.0"]
      # uses-sdk:minSdkVersion 15 cannot be smaller than version 21 declared in library [androidx.appcompat:appcompat-resources:1.7.1]
      - dependency-name: "androidx.appcompat:appcompat"
        versions: [ ">=1.7.0" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
