name: Setup Java

inputs:
  include-emulator-cache:
    description: 'Whether to cache/restore Android emulator images'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: '17'

    - name: Cache Gradle & Android SDK
      uses: actions/cache@v5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          /usr/local/lib/android/sdk/platforms
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Cache Android System Images
      if: ${{ inputs.include-emulator-cache == 'true' }}
      uses: actions/cache@v5
      with:
        path: |
          ~/.android/avd
          /usr/local/lib/android/sdk/system-images
        key: ${{ runner.os }}-android-images-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-android-images-

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
