name: Setup Java

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        add-job-summary: 'on-failure'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
