name: Appium Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Install Appium
        run: npm install -g appium

      - name: Install UIAutomator2
        run: appium driver install uiautomator2

      - name: Install dependencies
        run: npm install
        working-directory: ./tests

      - name: Start Appium server
        run: appium &

      - name: Run emulator and tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew assembleDebug && cd tests && npm run test
