name: Android CI

on:
  push:
    branches:
      - '**'
    # Tags are ignored since the release workflow calls this workflow
    # directly.
    tags-ignore:
      - '**'
  # Allow this workflow to be called by other workflows.
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-java

      - run: ./gradlew testDebugUnitTest

  instrumented-test:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      fail-fast: false
      matrix:
        device: [ pixel2Api26, pixel2Api28, pixel2Api30 ]
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-java
        with:
          device-name: ${{ matrix.device }}
          include-emulator-cache: 'true'

      - name: Enable KVM
        run: |
          if [ -e /dev/kvm ]; then
            sudo chmod 666 /dev/kvm
            echo "KVM is available and accessible."
          else
            echo "KVM is NOT available on this runner. Tests will be extremely slow."
            exit 1
          fi

      - name: Disable emulator console auth
        run: echo -n "" > ~/.emulator_console_auth_token

      - name: Run test on ${{ matrix.device }}
        run: ./gradlew :app:${{ matrix.device }}DebugAndroidTest -PtestMinSdk=26

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.device }}
          path: app/build/outputs/androidTest-results/managedDevice/
